### ISSUE TITLE
doc: Missing imports in README example

### ISSUE THREAD

**Issue by NaDasai** [chainbound/fiber-rs#17]
I just noticed that the imports are missing in this example:
https://github.com/chainbound/fiber-rs?tab=readme-ov-file#send_transaction
```rust
use reth_primitives::TransactionSigned;
```
It should probably be like the following one:
```rust
use reth_primitives::{Transaction, TxEip1559, Address, TransactionKind, AccessList, Signature, U256, TransactionSigned};
```

**Comment by mempirate** [comment]
Thanks for pointing this out! Feel free to open a PR if you have something ready, otherwise we'll do it soon :)
