### ISSUE TITLE
Migrate types to `alloy`

### ISSUE THREAD

**Issue by mempirate** [chainbound/fiber-rs#6]

**Comment by quangkeu95** [comment]
Is there any plan to do this?

**Comment by merklefruit** [comment]
Partially closed by #15, but still waiting to remove reth_primitives in favor of alloy when they are ready.

**Comment by merklefruit** [comment]
Actually, since we rely on types such as `PooledTransactionsElement`, we'll need reth_primitives as these won't be migrated over to Alloy. As such, the issue can be closed.
